import type { MetadataRoute } from 'next';

export default function sitemap(): MetadataRoute.Sitemap {
    const base = 'https://www.astroword.in';
    const now = new Date();

    return [
        {
            url: base,
            lastModified: now,
            changeFrequency: 'weekly',
            priority: 1.0,
        },

        {
            url: `${base}/darakaraka`,
            lastModified: now,
            changeFrequency: 'monthly',
            priority: 0.9,
        },
        {
            url: `${base}/atmakaraka`,
            lastModified: now,
            changeFrequency: 'monthly',
            priority: 0.9,
        },
        {
            url: `${base}/amatyakaraka`,
            lastModified: now,
            changeFrequency: 'monthly',
            priority: 0.9,
        },
        {
            url: `${base}/gana`,
            lastModified: now,
            changeFrequency: 'monthly',
            priority: 0.9,
        },
        {
            url: `${base}/manglik`,
            lastModified: now,
            changeFrequency: 'monthly',
            priority: 0.9,
        },
        {
            url: `${base}/dasha-calculator`,
            lastModified: now,
            changeFrequency: 'monthly' as const,
            priority: 0.9,
        },
        {
            url: `${base}/birth-tithi-calculator`,
            lastModified: now,
            changeFrequency: 'monthly' as const,
            priority: 0.9,
        },
        {
            url: `${base}/marriage-type`,
            lastModified: now,
            changeFrequency: 'monthly',
            priority: 0.9,
        },
        {
            url: `${base}/marriage-year`,
            lastModified: now,
            changeFrequency: 'monthly',
            priority: 0.9,
        },
        {
            url: `${base}/spouse-initial`,
            lastModified: now,
            changeFrequency: 'monthly',
            priority: 0.9,
        },
        {
            url: `${base}/upapada-lagna`,
            lastModified: now,
            changeFrequency: 'monthly' as const,
            priority: 0.9,
        },
        {
            url: `${base}/arudha-lagna`,
            lastModified: now,
            changeFrequency: 'monthly' as const,
            priority: 0.9,
        },
        {
            url: `${base}/kaal-sarp-dosha`,
            lastModified: now,
            changeFrequency: 'monthly' as const,
            priority: 0.9,
        },
        {
            url: `${base}/sade-sati`,
            lastModified: now,
            changeFrequency: 'monthly' as const,
            priority: 0.9,
        },
        {
            url: `${base}/moon-sign`,
            lastModified: now,
            changeFrequency: 'monthly' as const,
            priority: 0.9,
        },
        {
            url: `${base}/nakshatra-calculator`,
            lastModified: now,
            changeFrequency: 'monthly' as const,
            priority: 0.9,
        },
        {
            url: `${base}/lagna-calculator`,
            lastModified: now,
            changeFrequency: 'monthly' as const,
            priority: 0.9,
        },
        {
            url: `${base}/ishta-devata`,
            lastModified: now,
            changeFrequency: 'monthly' as const,
            priority: 0.9,
        },
        {
            url: `${base}/pitra-dosha`,
            lastModified: now,
            changeFrequency: 'monthly' as const,
            priority: 0.9,
        },
        {
            url: `${base}/d9-chart`,
            lastModified: now,
            changeFrequency: 'monthly' as const,
            priority: 0.9,
        },
        {
            url: `${base}/raja-yoga`,
            lastModified: now,
            changeFrequency: 'monthly' as const,
            priority: 0.9,
        },
        {
            url: `${base}/marriage-report`,
            lastModified: now,
            changeFrequency: 'monthly' as const,
            priority: 0.95,
        },
        {
            url: `${base}/kundali-matching`,
            lastModified: now,
            changeFrequency: 'monthly' as const,
            priority: 0.95,
        },
        {
            url: `${base}/blog`,
            lastModified: now,
            changeFrequency: 'weekly',
            priority: 0.8,
        },
        {
            url: `${base}/blog/what-is-darakaraka`,
            lastModified: now,
            changeFrequency: 'monthly',
            priority: 0.7,
        },
        {
            url: `${base}/blog/atmakaraka-meaning`,
            lastModified: now,
            changeFrequency: 'monthly',
            priority: 0.7,
        },
        {
            url: `${base}/blog/when-will-i-get-married-astrology`,
            lastModified: now,
            changeFrequency: 'monthly',
            priority: 0.7,
        },
        {
            url: `${base}/blog/love-or-arranged-marriage-astrology`,
            lastModified: now,
            changeFrequency: 'monthly',
            priority: 0.7,
        },
        {
            url: `${base}/blog/gana-matching-vedic-astrology`,
            lastModified: now,
            changeFrequency: 'monthly',
            priority: 0.7,
        },
        {
            url: `${base}/blog/d9-navamsa-chart-explained`,
            lastModified: now,
            changeFrequency: 'monthly',
            priority: 0.7,
        },
        {
            url: `${base}/blog/what-is-amatyakaraka`,
            lastModified: now,
            changeFrequency: 'monthly',
            priority: 0.7,
        },
        {
            url: `${base}/blog/gana-matching-marriage`,
            lastModified: now,
            changeFrequency: 'monthly',
            priority: 0.7,
        },
        {
            url: `${base}/blog/spouse-name-initial-nakshatra`,
            lastModified: now,
            changeFrequency: 'monthly',
            priority: 0.7,
        },
        {
            url: `${base}/blog/what-is-jaimini-astrology`,
            lastModified: now,
            changeFrequency: 'monthly',
            priority: 0.7,
        },
        {
            url: `${base}/blog/mars-7th-house-marriage`,
            lastModified: now,
            changeFrequency: 'monthly',
            priority: 0.7,
        },
        {
            url: `${base}/blog/venus-in-vedic-astrology`,
            lastModified: now,
            changeFrequency: 'monthly',
            priority: 0.7,
        },
        {
            url: `${base}/blog/rahu-in-7th-house`,
            lastModified: now,
            changeFrequency: 'monthly',
            priority: 0.7,
        },
        {
            url: `${base}/blog/what-is-manglik-dosha`,
            lastModified: now,
            changeFrequency: 'monthly',
            priority: 0.7,
        },
        {
            url: `${base}/blog/vimshottari-dasha-explained`,
            lastModified: now,
            changeFrequency: 'monthly',
            priority: 0.7,
        },
        {
            url: `${base}/blog/birth-tithi-astrology`,
            lastModified: now,
            changeFrequency: 'monthly',
            priority: 0.7,
        },
        {
            url: `${base}/blog/marriage-timing-astrology`,
            lastModified: now,
            changeFrequency: 'monthly',
            priority: 0.7,
        },
        {
            url: `${base}/blog/upapada-lagna-marriage`,
            lastModified: now,
            changeFrequency: 'monthly',
            priority: 0.7,
        },
        {
            url: `${base}/blog/arudha-lagna-public-image`,
            lastModified: now,
            changeFrequency: 'monthly',
            priority: 0.7,
        },
        {
            url: `${base}/blog/kaal-sarp-dosha-explained`,
            lastModified: now,
            changeFrequency: 'monthly',
            priority: 0.7,
        },
        {
            url: `${base}/blog/sade-sati-guide`,
            lastModified: now,
            changeFrequency: 'monthly',
            priority: 0.7,
        },
        {
            url: `${base}/blog/moon-sign-meaning`,
            lastModified: now,
            changeFrequency: 'monthly',
            priority: 0.7,
        },
        {
            url: `${base}/blog/nakshatra-secrets`,
            lastModified: now,
            changeFrequency: 'monthly',
            priority: 0.7,
        },
        {
            url: `${base}/blog/rising-sign-astrology`,
            lastModified: now,
            changeFrequency: 'monthly',
            priority: 0.7,
        },
        {
            url: `${base}/blog/find-ishta-devata`,
            lastModified: now,
            changeFrequency: 'monthly',
            priority: 0.7,
        },
        {
            url: `${base}/blog/pitra-dosha-remedies`,
            lastModified: now,
            changeFrequency: 'monthly',
            priority: 0.7,
        },
        {
            url: `${base}/blog/how-to-read-navamsa-chart`,
            lastModified: now,
            changeFrequency: 'monthly',
            priority: 0.7,
        },
        {
            url: `${base}/blog/vargottama-planets-meaning`,
            lastModified: now,
            changeFrequency: 'monthly',
            priority: 0.7,
        },
        {
            url: `${base}/blog/navamsa-lagna-all-12-signs`,
            lastModified: now,
            changeFrequency: 'monthly',
            priority: 0.7,
        },
        {
            url: `${base}/blog/raja-yoga-in-astrology`,
            lastModified: now,
            changeFrequency: 'monthly',
            priority: 0.7,
        },
        {
            url: `${base}/blog/gaja-kesari-yoga`,
            lastModified: now,
            changeFrequency: 'monthly',
            priority: 0.7,
        },
        {
            url: `${base}/blog/panch-mahapurusha-yoga`,
            lastModified: now,
            changeFrequency: 'monthly',
            priority: 0.7,
        },
        {
            url: `${base}/blog/neecha-bhanga-raja-yoga`,
            lastModified: now,
            changeFrequency: 'monthly' as const,
            priority: 0.8,
        },
        {
            url: `${base}/blog/dharma-karmadhipati-yoga`,
            lastModified: now,
            changeFrequency: 'monthly' as const,
            priority: 0.8,
        },
        {
            url: `${base}/disclaimer`,
            lastModified: now,
            changeFrequency: 'yearly' as const,
            priority: 0.1,
        },
        {
            url: `${base}/privacy-policy`,
            lastModified: now,
            changeFrequency: 'yearly',
            priority: 0.3,
        },
        {
            url: `${base}/terms`,
            lastModified: now,
            changeFrequency: 'yearly',
            priority: 0.3,
        },
        {
            url: `${base}/refund-policy`,
            lastModified: now,
            changeFrequency: 'yearly',
            priority: 0.3,
        },
        {
            url: `${base}/support`,
            lastModified: now,
            changeFrequency: 'monthly',
            priority: 0.4,
        },
        {
            url: `${base}/dashboard`,
            lastModified: now,
            changeFrequency: 'monthly',
            priority: 0.5,
        },
        {
            url: `${base}/daily-horoscope`,
            lastModified: now,
            changeFrequency: 'always',
            priority: 0.95,
        },
        {
            url: `${base}/blog/jaimini-kundali-matching`,
            lastModified: now,
            changeFrequency: 'monthly' as const,
            priority: 0.8,
        },
        {
            url: `${base}/blog/darakaraka-compatibility-marriage`,
            lastModified: now,
            changeFrequency: 'monthly' as const,
            priority: 0.8,
        },
        {
            url: `${base}/blog/navamsa-compatibility-marriage`,
            lastModified: now,
            changeFrequency: 'monthly' as const,
            priority: 0.8,
        },
        {
            url: `${base}/blog/nadi-dosha-cancellation`,
            lastModified: now,
            changeFrequency: 'monthly' as const,
            priority: 0.8,
        },
        {
            url: `${base}/blog/bhakoot-dosha-exceptions`,
            lastModified: now,
            changeFrequency: 'monthly' as const,
            priority: 0.8,
        },
        {
            url: `${base}/blog/upapada-lagna-compatibility`,
            lastModified: now,
            changeFrequency: 'monthly' as const,
            priority: 0.8,
        },
    ];
}
